#!/bin/bash
# To get homogenity of the data
# merge the data
prefix=imd_
#ls *$prefix*.nc
echo "working on :" $prefix
cdo mergetime *${prefix}*.nc ${prefix}_merge.nc
# requred time
yrs=1979
yre=2007
echo "time period:" $yrs "to" $yre
cdo selyear,$yrs/$yre ${prefix}_merge.nc data_${prefix}.nc
rm ${prefix}_merge.nc
# to crop
# Daily climatology
cdo ydaymean data_${prefix}.nc ${prefix}_day_clim1.nc
# monthly climatology
cdo ymonmean data_${prefix}.nc ${prefix}_monclim1.nc
###compute anomalies
cdo -ydaysub GPCP_DD_JJAS_1997_2015.nc -ydaymean GPCP_DD_JJAS_1997_2015.nc GPCP_DD_JJAS_1997_2015_anom.nc
;;; To create animated video with images
ffmpeg -framerate 4 -start_number 1 -i ./scripts/spatial_precipitation.%06d.png -pix_fmt yuv420p out1.mp4
